<?xml version="1.0" encoding="utf-8"?><Database Name="SgMinimog" Class="MinimogDbDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.36,1433;Initial Catalog=SgMinimog;User ID=manish.gupta" SettingsObjectName="Product.Data.Properties.Settings" SettingsPropertyName="SgMinimogConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetProductDataAsJsonResult" Method="GetProductDataAsJsonResult">
    <ElementType Name="GetProductDataAsJsonResultResult">
      <Column Name="JsonResult" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.procGetProductByIdAsJson" Method="procGetProductByIdAsJson">
    <Parameter Name="ProductId" Parameter="productId" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="procGetProductByIdAsJsonResult">
      <Column Name="JsonResult" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.procGetProductByIdAsJson_20230806" Method="procGetProductByIdAsJson_20230806">
    <Parameter Name="ProductId" Parameter="productId" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="procGetProductByIdAsJson_20230806Result">
      <Column Name="JsonResult" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.procGetProductDataAsJsonResult_20230806" Method="procGetProductDataAsJsonResult_20230806">
    <ElementType Name="procGetProductDataAsJsonResult_20230806Result">
      <Column Name="JsonResult" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.procLoginCheck" Method="procLoginCheck">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(60)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="procLoginCheckResult">
      <Column Name="IsValid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.procSaveUser" Method="procSaveUser">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="procSaveUserResult">
      <Column Name="IsValid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>